# terraform-generated workflow
name: Renovate

on:
  schedule:
  - cron: "0 17 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  renovate:
    uses: msdeleyto/gh-actions/.github/workflows/renovate.yaml@main
    secrets:
      RENOVATE_PRIVATE_KEY: ${{ secrets.RENOVATE_PRIVATE_KEY }}
